//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasketballCompetitionPlatform.DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StoredProcedursResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoredProcedursResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasketballCompetitionPlatform.DataAccess.StoredProcedursResources", typeof(StoredProcedursResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spAgreementRoom_Delete.
        /// </summary>
        internal static string AgreementRoom_Delete {
            get {
                return ResourceManager.GetString("AgreementRoom_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spAgreementRoom_Get.
        /// </summary>
        internal static string AgreementRoom_Get {
            get {
                return ResourceManager.GetString("AgreementRoom_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spAgreementRoom_GetAll.
        /// </summary>
        internal static string AgreementRoom_GetAll {
            get {
                return ResourceManager.GetString("AgreementRoom_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spAgreementRoom_Insert.
        /// </summary>
        internal static string AgreementRoom_Insert {
            get {
                return ResourceManager.GetString("AgreementRoom_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spAgreementRoom_RequestForChange_Delete.
        /// </summary>
        internal static string AgreementRoom_RequestForChange_Delete {
            get {
                return ResourceManager.GetString("AgreementRoom_RequestForChange_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spAgreementRoom_RequestForChange_Get.
        /// </summary>
        internal static string AgreementRoom_RequestForChange_Get {
            get {
                return ResourceManager.GetString("AgreementRoom_RequestForChange_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spAgreementRoom_RequestForChange_GetAll.
        /// </summary>
        internal static string AgreementRoom_RequestForChange_GetAll {
            get {
                return ResourceManager.GetString("AgreementRoom_RequestForChange_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spAgreementRoom_RequestForChange_Insert.
        /// </summary>
        internal static string AgreementRoom_RequestForChange_Insert {
            get {
                return ResourceManager.GetString("AgreementRoom_RequestForChange_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spAgreementRoom_RequestForChange_Update.
        /// </summary>
        internal static string AgreementRoom_RequestForChange_Update {
            get {
                return ResourceManager.GetString("AgreementRoom_RequestForChange_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spAgreementRoom_TeamLeave_Delete.
        /// </summary>
        internal static string AgreementRoom_TeamLeave_Delete {
            get {
                return ResourceManager.GetString("AgreementRoom_TeamLeave_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spAgreementRoom_TeamLeave_Get.
        /// </summary>
        internal static string AgreementRoom_TeamLeave_Get {
            get {
                return ResourceManager.GetString("AgreementRoom_TeamLeave_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spAgreementRoom_TeamLeave_GetAll.
        /// </summary>
        internal static string AgreementRoom_TeamLeave_GetAll {
            get {
                return ResourceManager.GetString("AgreementRoom_TeamLeave_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spAgreementRoom_TeamLeave_Insert.
        /// </summary>
        internal static string AgreementRoom_TeamLeave_Insert {
            get {
                return ResourceManager.GetString("AgreementRoom_TeamLeave_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spAgreementRoom_TeamLeave_Update.
        /// </summary>
        internal static string AgreementRoom_TeamLeave_Update {
            get {
                return ResourceManager.GetString("AgreementRoom_TeamLeave_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spAgreementRoom_Update.
        /// </summary>
        internal static string AgreementRoom_Update {
            get {
                return ResourceManager.GetString("AgreementRoom_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spBasketballCourt_Delete.
        /// </summary>
        internal static string BasketballCourt_Delete {
            get {
                return ResourceManager.GetString("BasketballCourt_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spBasketballCourt_Get.
        /// </summary>
        internal static string BasketballCourt_Get {
            get {
                return ResourceManager.GetString("BasketballCourt_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spBasketballCourt_GetAll.
        /// </summary>
        internal static string BasketballCourt_GetAll {
            get {
                return ResourceManager.GetString("BasketballCourt_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spBasketballCourt_Insert.
        /// </summary>
        internal static string BasketballCourt_Insert {
            get {
                return ResourceManager.GetString("BasketballCourt_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spBasketballCourt_Update.
        /// </summary>
        internal static string BasketballCourt_Update {
            get {
                return ResourceManager.GetString("BasketballCourt_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spEvent_Delete.
        /// </summary>
        internal static string Event_Delete {
            get {
                return ResourceManager.GetString("Event_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spEvent_Get.
        /// </summary>
        internal static string Event_Get {
            get {
                return ResourceManager.GetString("Event_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spEvent_GetAll.
        /// </summary>
        internal static string Event_GetAll {
            get {
                return ResourceManager.GetString("Event_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spEvent_Insert.
        /// </summary>
        internal static string Event_Insert {
            get {
                return ResourceManager.GetString("Event_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spEvent_Update.
        /// </summary>
        internal static string Event_Update {
            get {
                return ResourceManager.GetString("Event_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spGame_Delete.
        /// </summary>
        internal static string Game_Delete {
            get {
                return ResourceManager.GetString("Game_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spGame_Get.
        /// </summary>
        internal static string Game_Get {
            get {
                return ResourceManager.GetString("Game_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spGame_GetAll.
        /// </summary>
        internal static string Game_GetAll {
            get {
                return ResourceManager.GetString("Game_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spGame_Insert.
        /// </summary>
        internal static string Game_Insert {
            get {
                return ResourceManager.GetString("Game_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spGame_Update.
        /// </summary>
        internal static string Game_Update {
            get {
                return ResourceManager.GetString("Game_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spInvite_Get.
        /// </summary>
        internal static string Invite_Get {
            get {
                return ResourceManager.GetString("Invite_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spInvite_GetAll.
        /// </summary>
        internal static string Invite_GetAll {
            get {
                return ResourceManager.GetString("Invite_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spInvite_GetAll_ForAgreementRoomId.
        /// </summary>
        internal static string Invite_GetAll_ForAgreementRoomId {
            get {
                return ResourceManager.GetString("Invite_GetAll_ForAgreementRoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spInvite_GetAll_TeamIdReceived.
        /// </summary>
        internal static string Invite_GetAll_TeamIdReceived {
            get {
                return ResourceManager.GetString("Invite_GetAll_TeamIdReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spInvite_GetAll_TeamIdSended.
        /// </summary>
        internal static string Invite_GetAll_TeamIdSended {
            get {
                return ResourceManager.GetString("Invite_GetAll_TeamIdSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spInvite_Insert.
        /// </summary>
        internal static string Invite_Insert {
            get {
                return ResourceManager.GetString("Invite_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spInvite_Update.
        /// </summary>
        internal static string Invite_Update {
            get {
                return ResourceManager.GetString("Invite_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spTeam_Delete.
        /// </summary>
        internal static string Team_Delete {
            get {
                return ResourceManager.GetString("Team_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spTeam_Get.
        /// </summary>
        internal static string Team_Get {
            get {
                return ResourceManager.GetString("Team_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spTeam_GetAll.
        /// </summary>
        internal static string Team_GetAll {
            get {
                return ResourceManager.GetString("Team_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spTeam_Insert.
        /// </summary>
        internal static string Team_Insert {
            get {
                return ResourceManager.GetString("Team_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spTeam_Update.
        /// </summary>
        internal static string Team_Update {
            get {
                return ResourceManager.GetString("Team_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spTeamInAgreementRoom_Delete.
        /// </summary>
        internal static string TeamInAgreementRoom_Delete {
            get {
                return ResourceManager.GetString("TeamInAgreementRoom_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spTeamInAgreementRoom_Insert.
        /// </summary>
        internal static string TeamInAgreementRoom_Insert {
            get {
                return ResourceManager.GetString("TeamInAgreementRoom_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spTeamInEvent_Delete.
        /// </summary>
        internal static string TeamInEvent_Delete {
            get {
                return ResourceManager.GetString("TeamInEvent_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spTeamInEvent_Insert.
        /// </summary>
        internal static string TeamInEvent_Insert {
            get {
                return ResourceManager.GetString("TeamInEvent_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spTeamInGame_Delete.
        /// </summary>
        internal static string TeamInGame_Delete {
            get {
                return ResourceManager.GetString("TeamInGame_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spTeamInGame_Insert.
        /// </summary>
        internal static string TeamInGame_Insert {
            get {
                return ResourceManager.GetString("TeamInGame_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spVote_Delete.
        /// </summary>
        internal static string Vote_Delete {
            get {
                return ResourceManager.GetString("Vote_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spVote_Get.
        /// </summary>
        internal static string Vote_Get {
            get {
                return ResourceManager.GetString("Vote_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spVote_GetAll.
        /// </summary>
        internal static string Vote_GetAll {
            get {
                return ResourceManager.GetString("Vote_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spVote_GetAll_ForGameId.
        /// </summary>
        internal static string Vote_GetAll_ForGameId {
            get {
                return ResourceManager.GetString("Vote_GetAll_ForGameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spVote_GetAll_TeamIdReceived.
        /// </summary>
        internal static string Vote_GetAll_TeamIdReceived {
            get {
                return ResourceManager.GetString("Vote_GetAll_TeamIdReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spVote_GetAll_TeamIdSended.
        /// </summary>
        internal static string Vote_GetAll_TeamIdSended {
            get {
                return ResourceManager.GetString("Vote_GetAll_TeamIdSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spVote_Insert.
        /// </summary>
        internal static string Vote_Insert {
            get {
                return ResourceManager.GetString("Vote_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spVote_Update.
        /// </summary>
        internal static string Vote_Update {
            get {
                return ResourceManager.GetString("Vote_Update", resourceCulture);
            }
        }
    }
}
